### ISSUE TITLE
TG-PLUS using CPU instead of GPU resulting in significantly slower processing

### ISSUE THREAD

**Issue by wobblywhale** [km2ii/JP109A_TG-PLUS#2]
Firstly I'm running this with an AMD Ryzen 5950X and Nvidia GTX 1080ti. I have all packs installed and using the following simple mod.ini
```
TG-PLUS
# This is a JP109A_TG-PLUS profile.
# Note the first line cannot be removed.

M1:tecogan:4:TG-STD
M2:tecogan:4:SE-4X

V1.9
RES:1920
```

When I run this processing on a file using Safe mode I have observed only my CPU being utilised and my GPU untouched. And yes I have selected my GPU in the advanced tecogan settings.

Due to this, processing takes at least 5 times longer compared to the unmodded version of JAVPlayer which does utilise the GPU Cuda cores. A 15 second 1080p clip takes over 10 minutes to process on TG-PLUS compared to less than 2 minutes on the unmodded version. This makes it almost unusable for longer movies. 

Is this to be expected?

**Comment by km2ii** [comment]
I noticed that , caused running on the CPU because the cuda runtime support libraries could not be found in the system environment paths.I am not completely sure if this is the case you are talk about.
The solution is :
Find these dlls from the system or download from the Internet and copy them into the TGMAIN directory:
```
cublas64_10.dll
cudart64_101.dll
cudnn64_7.dll
cufft64_10.dll
curand64_10.dll
cusolver64_10.dll
cusparse64_10.dll
```

**Comment by wobblywhale** [comment]
The files fixed it, it's now processing with the GPU and performance is much better. Thank you!
