### ISSUE TITLE
Error while using veai

### ISSUE THREAD

**Issue by siqwew** [km2ii/JP109A_TG-PLUS#45]
![veai](https://user-images.githubusercontent.com/89594960/139687971-22ab032f-e176-4f05-bdb3-7c469c2e649b.jpg)

**Comment by siqwew** [comment]
TG-Plus for JP_109a v0.1.10.24
Topaz Video Enhance AI 2.3.0

**Comment by siqwew** [comment]
tg-se-veai-ue

**Comment by siqwew** [comment]
[main]
mode = TG-PLUS
autoren = ON
debug = OFF

[mplus]
m1 = tecogan:4:TG-STD
m2 = denoise:tla
m3 = tecogan:4:SE-4X-S1
m4 = veai:4:prob
m5 = downscale:4
m6 = tecogan:4:UE-4X
m7 = 
m8 = 
m9 = 
m10 = 

[others]
imgext = png
skip_imgs = 14
crf = 20
resolution = 1920

[veai]
veaipath = C:/Program Files/Topaz Labs LLC/Topaz Video Enhance AI/veai.exe

[veai_theia_model_opt]
sharpen = 15
enhance-detail = 50
reduce-noise = 0

[veai_proteus_model_opt]
compression = 52
details = 24
blur = 9
noise = 7
halo = 12
preblur = -19

[veaidict]
ahq = ahq-11
alq = alq-12
alqs = alqs-1
amq = amq-12
amqs = amqs-1
gcg = gcg-5
ghq = ghq-5
prob = prob-1
thd = thd-3
thf = thf-4

[Author]
discord = kmkii#8701
gmail = ty4king@gmail.com

[mplus01]
m1 = tecogan:4:TG-STD
m2 = denoise:tla
m3 = tecogan:4:SE-4X-S1
m4 = veai:4:prob
m5 = downscale:4
m6 = tecogan:4:UE-4X
m7 = 
m8 = 
m9 = 
m10 =

**Comment by km2ii** [comment]
1.This is caused by a conflict between multiple versions of veai, 
please check and remove all versions and reinstall veai 2.3.0.

2.Open a command line window and execute the following test.
  note the modification of the corresponding directory
![image](https://user-images.githubusercontent.com/55206195/139702650-27593c54-ae99-4b0b-89eb-f543e5e989d8.png)
"C:\Program Files\Topaz Labs LLC\Topaz Video Enhance AI\veai.exe" -i Z:\JavPlayer_109a\TG\input0\0000.png -o Z:\JavPlayer_109a\TG\output0 -s 4 -m prob-1 -f png

**Comment by siqwew** [comment]
Thank you
