### ISSUE TITLE
[tecogan-da] The number of files in input8 and output8 does not match

### ISSUE THREAD

**Issue by Delta45724** [km2ii/JP109A_TG-PLUS#99]
Hello I have this issue only when using tecigan-da.

I tried deleting all input and output folder but that did not work.

![image](https://user-images.githubusercontent.com/26705305/209416535-5ba1587f-e95f-45c6-b95f-b19b91db0574.png)

**Comment by Delta45724** [comment]
seems like the same issue here but I could not download that patch files
https://github.com/km2ii/JP109A_TG-PLUS/issues/91#issuecomment-1310637731

**Comment by Hellgate4** [comment]
The images in folder 8 are mosaic-free and are relatively large in size, resulting in a memory drop.
My solution is to change m1 to tecoGAN-da -> Bvpp x8 and proceed with Middle Resume.
The error did not occur because it took up less Bvppx8 resource memory than techoGAN-da.
It would be more useful to do a temporary measure or if there is a mosaic-free scene by crossing it or cutting it with a separate crop.

**Comment by Delta45724** [comment]
> The images in folder 8 are mosaic-free and are relatively large in size, resulting in a memory drop. My solution is to change m1 to tecoGAN-da -> Bvpp x8 and proceed with Middle Resume. The error did not occur because it took up less Bvppx8 resource memory than techoGAN-da. It would be more useful to do a temporary measure or if there is a mosaic-free scene by crossing it or cutting it with a separate crop.

interesting... yeah Bvppx8 works perfectly for me
